[options]
addons_path = /home/palankarta/odoo/odoo/addons,/home/palankarta/odoo/addons,/home/palankarta/odoo/custom_addons
db_host = False
db_port = False
db_user = odoo
db_password = odoo
logfile = odoo.log
xmlrpc_port = 8069
admin_passwd = $pbkdf2-sha512$600000$YGytdS6lFGJM6f3fO6eUsg$otOBr19eK1Wy5YsSKNEbpHbu3frR36XqlieriXEw9Ky33FFt6jyCs6tyn62ZJ4VwgDoKpyhFxJfKQZqIiblVhg

