[options]
addons_path = addons, custom_addons

; Database
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo

; Logging
logfile = /dev/stdout
log_level = info

; Server


; Security
admin_passwd = $pbkdf2-sha512$600000$YGytdS6lFGJM6f3fO6eUsg$otOBr19eK1Wy5YsSKNEbpHbu3frR36XqlieriXEw9Ky33FFt6jyCs6tyn62ZJ4VwgDoKpyhFxJfKQZqIiblVhg

; Optional Performance
limit_memory_soft = 671088640
limit_memory_hard = 805306368
limit_time_cpu = 60
limit_time_real = 120
workers = 2
max_cron_threads = 1

